package tk.ivybits.javi.format;

public enum SampleFormat {
    UNSIGNED_8BIT,
    SIGNED_16BIT,
    SIGNED_32BIT,
    SIGNED_FLOAT,
    SIGNED_DOUBLE,
    SIGNED_8BIT_PLANAR,
    SIGNED_16BIT_PLANAR,
    SIGNED_32BIT_PLANAR,
    SIGNED_FLOAT_PLANAR,
    SIGNED_DOUBLE_PLANAR
}
