package tk.ivybits.javi.swing;

/**
 * Listener for events generated by SwingMediaPanel playback.
 *
 * @version 1.0
 * @since 1.0
 */
public interface StreamListener {
    /**
     * Called when playback is finished.
     *
     * @since 1.0
     */
    void onEnd();
}
